# Generated by Django 5.2.3 on 2026-03-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.camera'),
        ),
    ]
